spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aerosign_data
    driver-class-name: org.postgresql.Driver
    username: vgair
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

secondary-datasource:
  url: jdbc:postgresql://localhost:5432/aerosign_service
  driver-class-name: org.postgresql.Driver
  username: vgair
  password: ""