spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aerosign_data
    driver-class-name: org.postgresql.Driver
    username: vgair
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.mail.ru
    port: 587
    username: your_mail@mail.ru
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

secondary-datasource:
  url: jdbc:postgresql://localhost:5432/aerosign_service
  driver-class-name: org.postgresql.Driver
  username: vgair
  password: ""